### ISSUE TITLE
OSError: file ./model/config.json not found

### ISSUE THREAD

**Issue by echo-zhai** [CrazyBoyM/dreambooth-for-diffusion#1]
dict_values(['./model/tokenizer/vocab.json', './model/tokenizer/merges.txt', None, './model/tokenizer/special_tokens_map.json', './model/tokenizer/tokenizer_config.json'])
Traceback (most recent call last):
  File "/usr/local/python3_8/lib/python3.8/site-packages/transformers/configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "/usr/local/python3_8/lib/python3.8/site-packages/transformers/utils/hub.py", line 297, in cached_path
    raise EnvironmentError(f"file {url_or_filename} not found")
OSError: file ./model/config.json not found

我本地部署的时候遇到一个问题，提示模型里找不到config.json文件？
环境： centos7
transformers：4.19.2

**Comment by CrazyBoyM** [comment]
Hi, you need to download the model files here:
https://github.com/KichangKim/DeepDanbooru/releases/download/v3-20211112-sgd-e28/deepdanbooru-v3-20211112-sgd-e28.zip

**Comment by CrazyBoyM** [comment]
可以检查下程序在本地读取的模型路径是否能正确读到

**Comment by echo-zhai** [comment]
检查过模型路径，转换为diffuser官方文件后，模型路径下确实是没有config.json文件的；检查了好几个模型都是这样的
# ls
feature_extractor  model_index.json  safety_checker  scheduler  text_encoder  tokenizer  unet  vae

**Comment by CrazyBoyM** [comment]
你的diffusers版本是多少  

pip list|grep diffusers

**Comment by CrazyBoyM** [comment]
你的diffusers版本是多少  

pip list|grep diffusers

**Comment by echo-zhai** [comment]
diffusers               0.7.2

**Comment by CrazyBoyM** [comment]
没道理唉，刚测试同样的版本在本地是正常的

**Comment by CrazyBoyM** [comment]
没道理唉，刚测试同样的版本在本地是正常的

**Comment by echo-zhai** [comment]
可以看下你的ckpt转换后的model目录下的文件么？

**Comment by echo-zhai** [comment]
解决了，transformers版本低了，升级了transformers版本ok了

**Comment by CrazyBoyM** [comment]
> 解决了，transformers版本低了，升级了transformers版本ok了

okk. 感谢提醒
