### ISSUE TITLE
汇报一个关于重复生成类图的问题

### ISSUE THREAD

**Issue by waterminer** [CrazyBoyM/dreambooth-for-diffusion#4]
我在使用这个镜像的时候，如果遇到了模型因为操作不当或者训练时间过长导致过拟合的情况我会选择回档
但是你这个镜像我目前找不到什么可以从中断点恢复的方法
而且如果我选择重新训练，哪怕class文件夹里已经有生成好的类图，它会重新生成一遍
有什么好办法吗？

**Comment by hhhyxnh** [comment]
注释掉这个一行
rm -rf $CLASS_DIR/
即在前面加一个 #
